language: python
cache: pip

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3

matrix:
  include:
    - language: generic
      python: 2.7
      os: osx
    - language: generic
      python: 3.3
      os: osx
    - language: generic
      python: 3.5
      os: osx
  allow_failures:
    - python: pypy3

install:
  - if [[ $TRAVIS_OS_NAME == osx ]]; then brew install openssl; fi
  - if [[ $TRAVIS_OS_NAME == osx ]]; then export LDFLAGS="-L$(brew --prefix openssl)/lib" CFLAGS="-I$(brew --prefix openssl)/include"; fi
  - pip install --upgrade pip virtualenv
  - virtualenv --python=python env
  - source env/bin/activate
  - make install

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

sudo: false
